COMPILER=g++
CPPFLAGS=-Wall -g -pedantic -pedantic-errors -std=c++11

almostincreasingsequence:
	$(COMPILER) $(CPPFLAGS) -o almostincreasingsequence almostincreasingsequence.cpp

clean:
	rm almostincreasingsequence
