COMPILER=g++
CPPFLAGS=-Wall -g -pedantic -pedantic-errors -std=c++11

makearrayconsecutive2:
	$(COMPILER) $(CPPFLAGS) -o makearrayconsecutive2 makearrayconsecutive2.cpp

clean:
	rm makearrayconsecutive2
