COMPILER=g++
CPPFLAGS=-Wall -g -pedantic -pedantic-errors -std=c++11

palindromerearranging:
	$(COMPILER) $(CPPFLAGS) -o palindromerearranging palindromerearranging.cpp

clean:
	rm palindromerearranging
