COMPILER=g++
CPPFLAGS=-Wall -g -pedantic -pedantic-errors -std=c++11

reverseinparenthesis:
	$(COMPILER) $(CPPFLAGS) -o reverseinparenthesis reverseinparenthesis.cpp

clean:
	rm reverseinparenthesis
