COMPILER=g++
CPPFLAGS=-Wall -g -pedantic -pedantic-errors -std=c++11

arraymaximaladjacentdifference:
	$(COMPILER) $(CPPFLAGS) -o arraymaximaladjacentdifference arraymaximaladjacentdifference.cpp

clean:
	rm arraymaximaladjacentdifference
