COMPILER=g++
CPPFLAGS=-Wall -g -pedantic -pedantic-errors -std=c++11

adjacentelementsproduct:
	$(COMPILER) $(CPPFLAGS) -o adjacentelementsproduct adjacentelementsproduct.cpp

clean:
	rm adjacentelementsproduct
